apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener-service
  template:
    metadata:
      labels:
        app: listener-service
    spec:
      containers:
      - name: listener-service
        image: "nabilwafi/listener-service:1.0.0"
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: 128Mi
            cpu: "500m"
          requests:
            memory: 64Mi
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: listener-service
spec:
  selector:
    app: listener-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80