openapi: 3.0.3
info:
  title: 'Category RESTful API'
  description: 'API spec for Category RESTful API'
  version: 1.0.0
server:
  - url: 'http://localhost:3000/api'
    description: 'local server'
paths:
  - '/categories':
    get:
      security:
        - CategoryAuth:
      tags:
        - 'Category API'
      description: 'List all categories'
      summary: 'List all categories'
      responses:
        '200':
          description: 'Success get all categories'
          content:
            'application/json':
              schema:
                code:
                  type: number
                status:
                  type: string
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/ResponseCategory'
    post:
      security:
        - CategoryAuth:
      tags:
        - 'Category API'
      description: 'Create new categories'
      summary: 'Create new categories'
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/RequestCategory'
      responses:
        200:
          description: 'Success Create Category'
          content:
            'application/json':
              schema:
                type: object
                properties:
                  type: object
                  properties:
                    code:
                      type: number
                    status:
                      type: string
                    data:
                      $ref: '#/components/schemas/ResponseCategory'
  - '/categories/{category_id}':
    get:
      security:
        - CategoryAuth:
      tags:
        - 'Category API'
      summary: 'Get category by id'
      description: 'Get category by id'
      parameters:
        - name: 'category_id'
          in: 'path'
          description: 'Category id'
      responses:
        200:
          description: 'Success get category'
          content:
            'application/json':
            schema:
              type: object
              properties:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/ResponseCategory'
    put:
      security:
        - CategoryAuth:
      tags:
        - 'Category API'
      summary: 'Update category by id'
      description: 'Update category by id'
      parameters:
        - name: 'category_id'
          in: 'path'
          description: 'Category id'
      requestBody:
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/RequestCategory'
      responses:
        200:
          description: 'Success put category'
          content:
            'application/json':
            schema:
              type: object
              properties:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/ResponseCategory'
    delete:
      security:
        - CategoryAuth:
      tags:
        - 'Category API'
      description: 'Delete categories'
      summary: 'Delete categories'
      responses:
        '200':
          description: 'Success delete category'
          content:
            'application/json':
              schema:
                code:
                  type: number
                status:
                  type: string
components:
  securityschemes:
    categoryAuth:
      type: 'apiKey'
      in: 'header'
      name: 'X-API-Key'
      description: 'Authentication for Category API'
  schemas:
    RequestCategory:
      type: object
      properties:
        name:
          type: string
    ResponseCategory:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
